#!/bin/sh
# build - Builds and tests NUnit

NANT="tools/nant/bin/NAnt.exe"
options="-f:scripts/nunit.build.targets"
config=""
runtime=""
clean=""
commands=""
passthru=false

for arg in $@
do
  if [ $passthru = true ]
  then
    commands="$commands $arg"
    continue
  fi

  case "$arg" in
    debug|release)
      config="$arg"
      ;;

    mono-3.5|3.5)
      runtime="mono-3.5"
      ;;

    clean)
      clean="clean"
      ;;

    test|test45|gui-test|gen-syntax)
      commands="$commands $arg"
      ;;

    -h|--help)
      echo "Builds and tests NUnit"
      echo
      echo "usage: BUILD [option [...] ]"
      echo
      echo "Options may be any of the following, in any order..."
      echo
      echo "  debug          Builds debug configuration (default)"
      echo "  release        Builds release configuration"
      echo
      echo "  mono-3.5, 3.5  Builds using Mono 3.5 profile (default)"
      echo
      echo "  clean          Cleans the output directory before building"
      echo "  clean-all      Removes output directories for all runtimes"
      echo
      echo "  test           Runs tests for a build using the console runner"
      echo "  test45         Run the .NET 4.5 async test assembly tests"
      echo "  gui-test       Runs tests for a build using the NUnit gui"
      echo
      echo "  -h, --help     Displays this help message"
      echo
      echo "Notes:"
      echo
      echo "  1. Tne 2.0 runtime version is targeted for NUnit itself." 
	  echo "     Tests use 3.5 or in some cases 4.5."
      echo   
      exit;
      ;;

    --)
      passthru=true
      ;;

    *)
      echo "Invalid argument: $arg"
      echo
      echo "Use $0 -h for more info"
      echo
      exit;
      ;;
  esac
done

if [ "$commands" = "" ]
then
  commands="build"
fi

if [ "$config" != "" ]
then
  options="$options -D:build.config=$config"
fi

if [ "$runtime" != "" ]
then
  options="$options -D:runtime.config=$runtime"
fi

exec mono "$NANT" $options $clean $commands


